name: Build and Package for RPM
on:
  push:
    tags:
      - '*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t screenvivid-rpm-build -f Dockerfile.rpm .

    - name: Package as .rpm
      run: |
        docker run --rm -v ${PWD}:/app screenvivid-rpm-build bash -c "
        cd screenvivid && python3 compile_resources.py && cd .. &&
        cd packaging/linux &&
        pyinstaller --clean --noconfirm screenvivid.spec &&
        rm dist/ScreenVivid/_internal/libstdc++.so.6 &&
        chmod +x build-rpm.sh &&
        ./build-rpm.sh '${GITHUB_REF_NAME}' &&
        mv screenvivid*.rpm /app/
        "

    - name: Upload Fedora package as artifact
      uses: actions/upload-artifact@v3
      with:
        name: screenvivid-${{ github.ref_name }}.rpm
        path: ./screenvivid*.rpm

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: screenvivid*.rpm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}